config/routes.rb
Rails.application.routes.draw do

  get "properties/tags" => "properties#tags", :as => :tags
  get "home/index"
  get "home/show"
  resources :search_suggestions
  root to: "activities#index"
  resources :comments, :only => [:create, :destroy]
  resources :activities
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users do
    resources :follows, :only => [:create, :destroy]
  end
  resources :lists do
    member do
      put 'add_property'
    end
    # collection do
    #   get 'search'
    # end
  end
  resources :properties do
    member do
     post 'add_to_list'
    end
  end
  resources :invites

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
end

app/models/list.rb
class List < ActiveRecord::Base
  include PublicActivity::Common
  #tracked owner: ->(controller, model) { controller && controller.current_user }
  acts_as_commentable
  acts_as_votable


  has_many :memberships
  has_many :users, :through => :memberships   #, :class_name => "User"

  has_many :propertyships
  has_many :properties, :through => :propertyships

  has_many :invites
  validates_presence_of :name


  def self.search(term)
    where("name like :term", term: "%#{term}%")
  end



  # searchable do
  #   text :name
  # end


  # def self.terms_for(prefix)
  #   suggestions = where("term like ?", "#{prefix}_%")
  #   suggestions.order("created_at asc").limit(10).map(&:term)
  # end
  #
  # def self.index_lists
  #   List.find_each do |list|
  #     index_term(list.name)
  #   end
  # end

  # before_destroy method overrides the default ruby destroy method that is called during dependent: :destroy
  # before_destroy :find_and_destroy_lists
  #
  # def find_and_destroy_lists
  #   activity = PublicActivity::Activity.find_by(trackable_id: self.id, trackable_type: self.class.name)
  #   if activity.present?
  #     activity.destroy
  #   end
  # end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_member, only: :show
  before_action :set_list, only: [:show, :edit, :update]

  def index
    @member = current_user.lists
    @lists = List.where(id: @member.ids).search(params[:search])
                 .page(params[:page]).per_page(5)

  end

  def show
    #byebug
    @invite = @list.invites.build
    @members = @list.user_ids
    @property_in_system = Property.where(:owner_id => current_user.id)
    @all_properties = Property.all
    @list = List.find(params[:id])
    @properties = @list.properties
    @hash = Gmaps4rails.build_markers(@properties) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      #   marker.picture({
      #                      :url => "http://www.spainbuyingguide.com/_assets/media/library/SP-mortgage.png",
      #                      :width => 32,
      #                      :height => 32
      #                  })

    end
    @comments = @list.comment_threads.order('created_at desc')
    @new_comment = Comment.build_from(@list, current_user.id, "")
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    @list.owner_id = current_user.id

    respond_to do |format|
      if @list.save
        @add_member = Membership.new
        @add_member.user_id =  @list.user_id
        @add_member.list_id = @list.id
        @add_member.save
        @list.create_activity :create, owner: current_user


        format.html { redirect_to lists_path, notice: 'List was successfully created.' }
      else
        format.html { render :new }
      end

    end
  end

  def edit
    @invite = @list.invites.build
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        @list.create_activity :update, owner: current_user

        format.html { redirect_to lists_path, notice: 'List was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @list = current_user.lists.find(params[:id])
    @activity = PublicActivity::Activity.find_by(trackable_id: (params[:id]), trackable_type: controller_path.classify)
    @activity.destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
    end
  end


  def add_property
    @list = List.find(params[:id])
    @members = @list.user_ids
    @mee = current_user.id

    if @mee.in?(@members)
      @l =  params[:list][:property_id]
      respond_to do |format|
        @propertiship = Propertyship.new
        @propertiship.list_id = @list.id
        @propertiship.property_id = @l
        if @propertiship.save
          @propertiship.create_activity :add_property, owner: current_user

          format.html { redirect_to list_path(@list), notice: 'Property Added' }
        else
          format.html { redirect_to list_path(@list), notice: 'Property Not Added' }
        end
      end
    else
      redirect_to :root
    end
  end




  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :user_id, :property_ids => [])
  end

  def invite_params
    params.require(:user).permit( :email, :name, :user_id, :list_id)
  end

  def authenticate_member
    @list = List.find(params[:id])
    @members = @list.user_ids
    @mee = current_user.id
    redirect_to :root unless @mee.in?(@members)
  end

  def authenticate_owner
    @list = List.find(params[:id])
    redirect_to :root unless current_user.id == @list.owner_id
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
  <%= form_for(@list) do |f| %>

      <% if @list.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

            <ul>
              <% @list.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>


        <%= f.text_field :name, autofocus: true %>
        <%= f.hidden_field :user_id  %>

        <%= f.submit 'Add List', class: 'btn btn-primary'%>
  <% end %>

app/views/lists/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-md-4">


<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>


    </div>
  </div>
</div>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-md-4">

<script type="text/javascript"  >
    jQuery(function() {
        return $('#search').autocomplete({
            source: "/search_suggestions"
        });
    });
</script>

<%= form_tag lists_path ,:method => :get do %>
  <div class="row">
    <%= text_field_tag :search, params[:search], :autocomplete => 'on',style: "width: 60%" %>
    <%= submit_tag "search", class: "btn btn-info" %>
  </div>

<% end %>

<h1><%= link_to "All activities", activities_path %></h1>

<h1>My Lists</h1>

    <% @lists.each do |list| %>


        <div class="bg-primary" style="padding: 10px; font-family: bold; color: black "> <%= link_to  list.name, list_path(list), class:  "bg-primary" %> </div>
        <div class="bg-info">
        <%=  link_to "show", list_path(:id => list.id) %>
        <% if current_user.id == list.owner_id %>
            <%= link_to 'Edit', edit_list_path(list) %>
            <%= link_to 'Destroy', list_path(list), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </div>
        <br>

    <% end %>
      <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
<br>

<%= link_to 'New List', new_list_path, class: "btn btn-primary" %>
</div>
</div>
</div>
</div>

app/views/lists/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-md-4">

<h3>Create A New List</h3>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>


    </div>
  </div>
</div>

app/views/lists/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-md-3 ">
        <%= form_for @invite , :url => invites_path do |f| %>
            <%= f.hidden_field :list_id, :value => @invite.list_id %>
            <%= f.email_field :email, placeholder: "Email" %>
            <%= f.submit 'Invite User', class: 'btn-primary' %>
        <% end %>
<br>
<br>
      <div>
      <% if @all_properties.present? %>
          <%= form_for(@list, url: add_property_list_path,  :method => :put) do |f| %>
              <div>
                <%= f.collection_select(:property_id, Property.all, :id, :street_address, {:prompt=>true}, {class: "form-control custom-button"} ) %>
              </div>
              <%= f.submit "Add Property", class: "btn btn-primary  custom-button" %>
          <% end %>
      <% else %>
          <%= link_to "Add new property",new_property_path %>
      <% end %>
    </div>
    </div>
    <div class="col-md-6">

    <h3>List Name: <%= @list.name %></h3>
    <% if current_user.id == @list.owner_id %>
    <%= link_to 'Edit', edit_list_path(@list) %> |
    <% end %>
    <%= link_to 'Back', lists_path %>


    <% if @properties.present? %>


        <div style='width: 800px;'>
          <div id="map" style='width: 600px; height: 400px;'></div>
        </div>

        <script type = "text/javascript">
            handler = Gmaps.build('Google');
            handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                markers = handler.addMarkers(<%=raw @hash.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
            });
        </script>

    <% end %>
<br>
<br>
      <h1>All Properties in this List</h1>
      <% @properties.each do |property| %>
          <div class="bg-primary" style="padding: 20px; font-family: bold; color: black ">
              <% if property.photo_url.thumb.url.present? %>
                <td><%= image_tag property.photo_url.thumb.url.to_s, alt: "property Image" %></td>
            <% else %>
                <td><%= image_tag "thumb_plogo.jpg" %></td>
            <% end %>
              <%= link_to property.street_address,property_path(id: property.id), class:  "bg-primary" , style: "padding-left: 50px;" %>
              <%= link_to "show",property_path(id: property.id), class:  "bg-primary", style: "float: right;" %>
          </div>
          <br>
      <% end %>
    </div>
  </div>
</div>
    <br>
    <br>
    <br>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-1">

    </div>
      <div class="col-md-5 ">

        <div class="event">
          <p><%= pluralize(@list.comment_threads.size, "comment") %> in this list  </p>
        </div>

        <div class="comments">
          <h2>Comments</h2>
          <%= render :partial => 'comments/form', :locals => { :comment => @new_comment } %>
          <%= render :partial => 'comments/comment', :collection => @comments, :as => :comment %>
        </div>
        </div>
      </div>
</div>
<%# render 'shared/actions', resource: @list %>
<!--<span class="like-count"><%# pluralize(@list.cached_votes_up, 'like') %></span>-->