config/routes.rb
Rails.application.routes.draw do

  get "properties/tags" => "properties#tags", :as => :tags
  get "home/index"
  get "home/show"
  resources :search_suggestions
  root to: "activities#index"
  resources :comments, :only => [:create, :destroy]
  resources :activities
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users do
    resources :follows, :only => [:create, :destroy]
  end
  resources :lists do
    member do
      put 'add_property'
    end
    # collection do
    #   get 'search'
    # end
  end
  resources :properties do
    member do
     post 'add_to_list'
    end
  end
  resources :invites

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
end

app/models/property.rb
class Property < ActiveRecord::Base
  mount_uploader :photo_url, ImageUploader
  serialize :pictures, Array
  mount_uploaders :pictures, ImageUploader
  include PublicActivity::Common

  has_many :propertyships
  has_many :lists, :through => :propertyships

  acts_as_taggable_on :tags
  acts_as_commentable
  acts_as_votable
  geocoded_by :street_address
  after_validation :geocode


  def self.search(term)
    where("street_address like :term", term: "%#{term}%")
  end


end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_owner, only: [:edit, :update, :destroy]


  def index
    @properties = Property.where(owner_id: current_user.id).page(params[:page]).per_page(10)
  end


  def show
    @current_user_lists = current_user.lists
    @property = Property.find(params[:id])

    @hash = Gmaps4rails.build_markers(@property) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      #   marker.picture({
      #                      :url => "http://www.spainbuyingguide.com/_assets/media/library/SP-mortgage.png",
      #                      :width => 32,
      #                      :height => 32
      #                  })

    end

    @tags_ids = @property.tag_list

    @tags = ActsAsTaggableOn::Tag.where(:id => @tags_ids)

    @comments = @property.comment_threads.order('created_at desc')
    @new_comment = Comment.build_from(@property, current_user.id, "")


  end


  def new
    @property = Property.new
  end


  def edit
    @tags_ids = @property.tag_list
    @tags = ActsAsTaggableOn::Tag.where(:id => @tags_ids)
  end


  def create
    @property = Property.new(property_params)
    @property.owner_id = current_user.id
    respond_to do |format|
      if @property.save
        @property.create_activity :create, owner: current_user

        format.html { redirect_to property_path(@property), notice: 'Property was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def update
    @property = Property.find(params[:id])
    respond_to do |format|
      if @property.update_attributes(property_params)
         @property.create_activity :update, owner: current_user

        format.html { redirect_to property_path(@property), notice: 'Property was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy


    @activity = PublicActivity::Activity.find_by(trackable_id: (params[:id]), trackable_type: controller_path.classify)
    @activity.destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to list_properties_path(@list), notice: 'Property was successfully destroyed.' }
    end
  end


  def like
    @property = Property.find(params[:id])
    @property.liked_by current_user

    if request.xhr?
      render json: { count: @property.get_likes.size, id: params[:id] }
    else
      redirect_to @property
    end
  end



  def add_to_list
    @property = Property.find(params[:id])
    @l =  params[:property][:list_id]

    respond_to do |format|
      @propertiship = Propertyship.new
      @propertiship.property_id = @property.id
      @propertiship.list_id = @l
      if @propertiship.save
        @property.create_activity :add_to_list, owner: current_user
        format.html { redirect_to property_path(@property), notice: 'Property Added' }
      else
        format.html { redirect_to property_path(@property), notice: 'Property Not Added' }
      end
    end
  end



    def tags
      query = params[:q]
      if query[-1,1] == " "
        query = query.gsub(" ", "")
        ActsAsTaggableOn::Tag.find_or_create_with_like_by_name(query)
      end

      @tags = ActsAsTaggableOn::Tag.where("tags.name LIKE ?", "%#{query}%")
      respond_to do |format|
        format.json { render :json => @tags.map{|t| {:id => t.name, :name => t.name }}}
      end
    end


  private

    def property_params
      params.require(:property).permit(:tag_list ,:street_address, :city, :state, :lat, :lon, :url , :photo_url, :description, :tags, :bedroom, :bathroom, :price, :status,:remote_photo_url_url,{:list_ids => []}, pictures: [])
    end

    def authenticate_owner
      @property = Property.find(params[:id])
      redirect_to :root unless current_user.id == @property.owner_id
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<!-- google maps -->

<!-- jquery -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<!-- jquery UI -->
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/gmaps/0.4.22/gmaps.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery.tokeninput/1.6.0/jquery.tokeninput.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.js"></script>

<script  type="text/javascript" >

    jQuery(function() {
        var completer;

        completer = new GmapsCompleter({
            inputField: '#gmaps-input-address',
            errorField: '#gmaps-error'
        });

        completer.autoCompleteInit({
            country: "us"
        });
    });

</script>
<script  type="text/javascript" >
    $(function() {
        $("#property_tag_list").tokenInput("/properties/tags.json", {
            prePopulate: $("#property_tag_list").data("pre"),
            preventDuplicates: true,
            theme: "facebook",
            allowCustomEntry: true,
            noResultsText: "'No result, hit space to create a new tag'"
        });
    });
</script>

<script>
    $(function() { $('#tags').tagsInput(); });
</script>

<div class="container ">

<div style="width: 30%" >

<%= simple_form_for @property, :html => { :multipart => true } do |f| %>


    <%= f.input :street_address, :input_html =>{:id => 'gmaps-input-address'}, :placeholder => 'Street Address...' %>
    <div id='gmaps-error'></div>

    <%# f.association :lists, as: :check_boxes %>
    <%= f.input :status, :collection => [ "Not For Sale", "For Sale", "For Rent"],:selected => "Not For Sale" %>


    <%= f.input :city,  as: :hidden %>
    <%= f.input :state, as: :hidden  %>
    <%= f.input :latitude,  as: :hidden  %>
    <%= f.input :longitude,  as: :hidden %>
    <%= f.input :url,:placeholder => "Property Url", :input_html => { id: "tags" } %>
    <%= f.input :remote_photo_url_url, :placeholder => "Image Url" %>
    <%= f.input :pictures, as: :file,:label => "Images", :placeholder => "Photo Url", :input_html => { multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png" } %>
    <%= f.input :bedroom ,:placeholder => "Beds" %>
    <%= f.input :bathroom , :placeholder => "Baths" %>
    <%= f.input :price, :placeholder => "Add Price" %>

    <%= f.input :description,:placeholder => "Description" %>
    <%= f.input :tag_list,:placeholder => "Tags",:input_html => { "data-pre" => @property.tags.map(&:attributes).to_json } %>

    <%= f.button :submit, "Create" %>
<% end %>


</div>
</div>

app/views/properties/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-md-4">

<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', property_path %> |
<%= link_to 'Back', properties_path %>

    </div>
  </div>
</div>

app/views/properties/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->


<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-md-4">
<h1>My Properties</h1>

      <% @properties.each do |property| %>
          <div class="bg-primary" style="padding: 20px; font-family: bold; color: black ">
            <p class= "bg-primary">
              <%= image_tag property.photo_url.thumb.url  %>
              <%= link_to property.street_address,property_path(id: property.id), class:  "bg-primary" %>
            </p>
          </div>
          <%=  link_to "show", property_path(:id => property.id) %>
          <%=  link_to "Edit", edit_property_path(:id => property.id) %>
          <%=  link_to "Delete", property_path(:id => property.id) ,method: :delete, data: { confirm: "Are you sure?" } %>
          <br>

    <% end %>

      <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
<br>
<%= link_to 'Back', lists_path %>
<%= link_to 'New Property', new_property_path %>


</div>
</div>
</div>
</div>

app/views/properties/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-md-4">

<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

    </div>
  </div>
</div>

app/views/properties/show.html.erb
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<style type="text/css">

    .hovergallery img{
        -webkit-transform:scale(0.8); /*Webkit: Scale down image to 0.8x original size*/
        -moz-transform:scale(0.8); /*Mozilla scale version*/
        -o-transform:scale(0.8); /*Opera scale version*/
        -webkit-transition-duration: 0.5s; /*Webkit: Animation duration*/
        -moz-transition-duration: 0.5s; /*Mozilla duration version*/
        -o-transition-duration: 0.5s; /*Opera duration version*/
        opacity: 0.7; /*initial opacity of images*/
        margin: 0 10px 5px 0; /*margin between images*/
    }

    .hovergallery img:hover{
        -webkit-transform:scale(1.1); /*Webkit: Scale up image to 1.2x original size*/
        -moz-transform:scale(1.1); /*Mozilla scale version*/
        -o-transform:scale(1.1); /*Opera scale version*/
        box-shadow:0px 0px 30px gray; /*CSS3 shadow: 30px blurred shadow all around image*/
        -webkit-box-shadow:0px 0px 30px gray; /*Safari shadow version*/
        -moz-box-shadow:0px 0px 30px gray; /*Mozilla shadow version*/
        opacity: 1;
    }

</style>



<div class="well">
  <div class="container-fluid">
    <div class="row" style="margin-left: 2.5%">

      <div class="row" style="margin-left: 30%; margin-right: 30%">
        <%= form_tag lists_path ,:method => :get do %>
            <div class="row">
              <%= text_field_tag :search, params[:search], :autocomplete => 'on',style: "width: 60%" %>
              <%= submit_tag "search", class: "btn btn-info" %>
            </div>
        <% end %>
      </div>

      <br>
      <br>
      <br>
      <div class="row">
        <div class="col-md-2" >
          <% if current_user.id == @property.owner_id %>
              <%= link_to 'Edit', edit_property_path(  :id => @property.id), class: "btn btn-primary custom-button" %>
          <% end %>
          <br><br><br>
          <div style="width: 80%">
            <h5>My lists</h5>
            <%= form_for(@property, url: add_to_list_property_path,  :method => :POST) do |f| %>
                <div>
                <%= f.collection_select(:list_id, @current_user_lists, :id, :name,{:prompt=>true}, {class: "form-control custom-button"})  %>
                <%= f.submit  "Add to list", class: "btn btn-primary custom-button" %>
                </div>
            <% end %>
          </div>
        </div>
        <div class="col-md-1">
        </div>
        <div class="col-md-9">
          <div class="row">
            <h4><%=   @property.street_address %> </h4>
            <div class="col-lg-5 hovergallery">
              <p>
                <% if @property.pictures.present? %>
                    <% @property.pictures.each do |p| %>
                        <%= image_tag(p.url().to_s, size: "120x120") %>
                    <% end %>
                <% else %>
                    <%= image_tag "plogo.jpg" %>
                <% end %>

                <% if @property.photo_url_url().present? %>
                    <%= image_tag @property.photo_url_url().to_s, size: "120x120" %>
                <% else %>
                    <%= image_tag "plogo.jpg" %>
                <% end %>
              </p>
            </div>

            <div class="col-md-4"  style="margin-left: 10px">
              <% if @property.present? %>
                  <div style='width: 400px;'>
                    <div id="map" style='width: 350px; height: 350px;'></div>
                  </div>

                  <script type = "text/javascript">
                      handler = Gmaps.build('Google');
                      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                          markers = handler.addMarkers(<%=raw @hash.to_json %>);
                          handler.bounds.extendWith(markers);
                          handler.fitMapToBounds();
                          handler.getMap().setZoom(14);
                      });
                  </script>
              <% end %>
            </div>
          </div>

          <div class="row">
            <p>
              <strong>Urls:</strong>
              <% if @property.url.present?  %>
              <% urls = @property.url.split(",") %>
                  <% urls.each do |p| %>
                      <p><%= link_to "#{p}", p %><p>
                  <% end %>
              <% end %>
            </p>

            <p>
              <strong>Description:</strong>
              <%= @property.description %>
            </p>

            <p>
              <strong>Bedroom:</strong>
              <%= @property.bedroom %>
            </p>

            <p>
              <strong>Bathroom:</strong>
              <%= @property.bathroom %>
            </p>

            <p>
              <strong>Price:</strong>
              <%= @property.price %>
            </p>

            <p>
              <strong>Status:</strong>
              <%= @property.status %>
            </p>

            <p>
              <strong>Tags:</strong>
              <%= @property.tag_list %>
            </p>

          </div>
          <p >
            <%= render 'shared/actions', resource: @property %>
            <span class="like-count"><%= pluralize(@property.cached_votes_up, 'like') %></span>
          </p>
        </div>
        <%# link_to 'Back', "#" %>
      </div>
    </div>
  </div>
<br><br>
<br><br>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-1">
      </div>
      <div class="col-md-5 ">


        <div class="comments">
          <h2>Comments</h2>
          <%= render :partial => 'comments/form', :locals => { :comment => @new_comment } %>
          <%= render :partial => 'comments/comment', :collection => @comments, :as => :comment %>
        </div>
      </div>
    </div>
  </div>
</div>