config/routes.rb
Rails.application.routes.draw do

  get "properties/tags" => "properties#tags", :as => :tags
  get "home/index"
  get "home/show"
  resources :search_suggestions
  root to: "activities#index"
  resources :comments, :only => [:create, :destroy]
  resources :activities
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users do
    resources :follows, :only => [:create, :destroy]
  end
  resources :lists do
    member do
      put 'add_property'
    end
    # collection do
    #   get 'search'
    # end
  end
  resources :properties do
    member do
     post 'add_to_list'
    end
  end
  resources :invites

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 before_action :authenticate_user!
  def index
    @users = User.all
  end

 def show
   @member = current_user.lists
   @lists = List.where(id: @member.ids).search(params[:search])
                .page(params[:page]).per_page(5)

   @properties = Property.search(params[:search])
                .page(params[:page]).per_page(5)
 end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="well">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-6">
        <h1>All Real Estates Users</h1>

<% @users.each do |user| %>
    <div class="row">
      <div class="col-md-5">
        <p><%= image_tag avatar_url(user) %> <%=  "#{full_name(user)}"%></p>
      </div>
        <div id="follow_user" class="col-md-1">
          <%= render :partial => "shared/follow_user", :locals => {:user => user} %>
        </div>
    </div>
    <br>
<% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-md-4">
      <%= form_tag home_show_path ,:method => :get do %>
          <div class="row">
            <%= text_field_tag :search, params[:search], :autocomplete => 'on',style: "width: 70%" %>
            <%= submit_tag "search", class: "btn btn-info" %>
          </div>

      <% end %>

      <br>
      <br>

    <% if @lists.present? %>
        <% @lists.each do |list| %>
            <div class="bg-primary" style="padding: 10px; font-family: bold; color: black "> <%= link_to  list.name, list_path(list), class:  "bg-primary" %> </div>
        <% end %>
        <br>
    <% end %>
    <br>
    <% if @properties.present? %>
        <% @properties.each do |property| %>
            <div class="bg-primary" style="padding: 20px; font-family: bold; color: black ">
              <p class= "bg-primary">
                <%= image_tag property.photo_url.thumb.url  %>
                <%= link_to property.street_address,property_path(id: property.id), class:  "bg-primary" %>
              </p>
            </div>
            <br>
        <% end %>
    <% end %>

    </div>
  </div>
</div>