config/routes.rb
Rails.application.routes.draw do

  get "properties/tags" => "properties#tags", :as => :tags
  get "home/index"
  get "home/show"
  resources :search_suggestions
  root to: "activities#index"
  resources :comments, :only => [:create, :destroy]
  resources :activities
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users do
    resources :follows, :only => [:create, :destroy]
  end
  resources :lists do
    member do
      put 'add_property'
    end
    # collection do
    #   get 'search'
    # end
  end
  resources :properties do
    member do
     post 'add_to_list'
    end
  end
  resources :invites

  match :like, to: 'likes#create', as: :like, via: :post
  match :unlike, to: 'likes#destroy', as: :unlike, via: :post
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!


  def index

    @friends = current_user.all_following.unshift(@user)
    @activities = PublicActivity::Activity.order("created_at desc").where(owner_id: @friends).page(params[:page]).per_page(10)  #or where(list_id: @membership.lists)

  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-3 ">
    <br><br><br>
    <div style="padding: 5px" class="row" ><%= link_to 'Add Property', new_property_path, class:"btn btn-primary btn-lg  custom-button" %></div>
    <div style="padding: 5px" class="row"><%= link_to 'Add List', new_list_path,class:"btn btn-primary btn-lg   custom-button"  %></div>
    <div style="padding: 5px" class="row"><%= link_to 'My Lists', lists_path,class:"btn btn-primary btn-lg  custom-button"  %></div>
    <div style="padding: 5px" class="row"><%= link_to 'My Properties', properties_path,class:"btn btn-primary btn-lg  custom-button"  %></div>
    <div style="padding: 5px" class="row"><%= link_to "Find Friends", home_index_path ,class:"btn btn-primary btn-lg  custom-button"  %></div>
    <div style="padding: 5px" class="row"><%= link_to "#{current_user.first_name}", user_path(:id => current_user.id),class:"btn btn-primary btn-lg  custom-button"  %></div>
  </div>
  <div class="col-md-8">
    <%= form_tag home_show_path ,:method => :get do %>
        <div class="row">
          <%= text_field_tag :search, params[:search], :autocomplete => 'on',style: "width: 50%" %>
          <%= submit_tag "search", class: "btn btn-info" %>
        </div>

    <% end %>
    <h1>Latest Activities</h1>

    <% @activities.each do |activity| %>
        <div class="activity">
          <div class="bg-primary" style="padding: 10px">
            <h4><%= link_to( "@#{activity.owner.first_name}" , activity.owner  , class: "activity-color" ) if activity.owner%><span  class= "activity-color" style="float: right; font-size: .7em" > <%= "  #{ time_ago_in_words(activity.created_at)}" + " ago" %></span>
            <p class= "activity-color"><%= render_activity activity  %></p></h4>
          </div>
        </div>
    <% end %>
    <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

  </div>
</div>
</div>